name: Terraform Feature Branch - Plan

on:
  push:
    branches:
      - "feature/**"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/prod

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login Using Service Principal
        run: |
          az login \
            --service-principal \
            --username "06af6e6f-6ae8-453b-a6b0-45da51045af3" \
            --password "Xo.8Q~RwPrQunA19YJTdqwKRZPEyXDZ3nl89-cjk" \
            --tenant "91695fd6-371b-4c10-8dc9-21e31d347ad6"

          az account set \
            --subscription "b299f192-d573-4040-b542-2aff90a974b5"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color